blank_issues_enabled: false
contact_links:
  - name: Ask a question / 質問する
    url: https://github.com/mtermapp/mterm-community/discussions
    about: Please ask and answer questions here. / 質問や議論はこちらのDiscussionsで行ってください。
